pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/lucas_lembo/.config/pgadmin4/config.json"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - LANGUAGE: pt_BR:pt:en
  - USER: lucas_lembo
  - SSH_AGENT_PID: 3509
  - XDG_SESSION_TYPE: x11
  - SHLVL: 0
  - HOME: /home/lucas_lembo
  - DESKTOP_SESSION: ubuntu
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GTK_MODULES: gail:atk-bridge
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - MANAGERPID: 3214
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1001/bus
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 8328
  - IM_CONFIG_PHASE: 1
  - LOGNAME: lucas_lembo
  - _: /usr/bin/dbus-update-activation-environment
  - JOURNAL_STREAM: 8:62646
  - XDG_SESSION_CLASS: user
  - USERNAME: lucas_lembo
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - WINDOWPATH: 2
  - PATH: /home/lucas_lembo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/lucas_lembo/.local/share/JetBrains/Toolbox/scripts
  - SESSION_MANAGER: local/Note-Lucas:@/tmp/.ICE-unix/3548,unix/Note-Lucas:/tmp/.ICE-unix/3548
  - INVOCATION_ID: a442f7b2a8844d538a9fd124826a7f73
  - XDG_RUNTIME_DIR: /run/user/1001
  - XDG_MENU_PREFIX: gnome-
  - DISPLAY: :0
  - LANG: pt_BR.UTF-8
  - XDG_CURRENT_DESKTOP: Unity
  - XAUTHORITY: /run/user/1001/gdm/Xauthority
  - XDG_SESSION_DESKTOP: ubuntu
  - XMODIFIERS: @im=ibus
  - SSH_AUTH_SOCK: /run/user/1001/keyring/ssh
  - SHELL: /bin/bash
  - QT_ACCESSIBILITY: 1
  - GDMSESSION: ubuntu
  - GPG_AGENT_INFO: /run/user/1001/gnupg/S.gpg-agent:0:1
  - GJS_DEBUG_OUTPUT: stderr
  - QT_IM_MODULE: ibus
  - PWD: /home/lucas_lembo
  - XDG_DATA_DIRS: /usr/share/ubuntu:/home/lucas_lembo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - CHROME_DESKTOP: pgadmin4.desktop
  - ORIGINAL_XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - ELECTRON_ENABLE_SECURITY_WARNINGS: false
  - GDK_BACKEND: x11
  - PGADMIN_INT_PORT: 44417
  - PGADMIN_INT_KEY: b0b5dafb-57cb-4926-9aa9-a37435332c50
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.005 Sec
2025-04-25 08:49:34,887: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 7.046 Sec
------------------------------------------
Total launch time of pgAdmin4: 7.211 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:44417/?key=b0b5dafb-57cb-4926-9aa9-a37435332c50
2025-04-25 09:39:52,530: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 6447088):
Error Message:ERROR:  column "idAprovacao" named in key does not exist
LINE 74:     PRIMARY KEY ("idAprovacao")
             ^ 

SQL state: 42703
Character: 2167

2025-04-25 09:41:16,876: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 3352993):
Error Message:ERROR:  current transaction is aborted, commands ignored until end of transaction block 

SQL state: 25P02

2025-04-25 09:41:21,473: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 9261948):
Error Message:ERROR:  current transaction is aborted, commands ignored until end of transaction block 

SQL state: 25P02

2025-04-25 09:41:22,875: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 7920468):
Error Message:ERROR:  current transaction is aborted, commands ignored until end of transaction block 

SQL state: 25P02

2025-04-25 09:48:42,372: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 1588448):
Error Message:ERROR:  column "idSerie" named in key does not exist
LINE 101:     PRIMARY KEY ("idSerie")
              ^ 

SQL state: 42703
Character: 2724

2025-04-25 09:49:46,479: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4215540(Query-id: 23962):
Error Message:ERROR:  foreign key constraint "idEscola" cannot be implemented
Key columns "idEscola" and "idEscola" are of incompatible types: integer and character varying[]. 

SQL state: 42804
Detail: Key columns "idEscola" and "idEscola" are of incompatible types: integer and character varying[].

2025-04-25 09:51:42,532: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:4641684(Query-id: 1874196):
Error Message:ERROR:  foreign key constraint "idEscola" cannot be implemented
Key columns "idEscola" and "idEscola" are of incompatible types: character varying and character varying[]. 

SQL state: 42804
Detail: Key columns "idEscola" and "idEscola" are of incompatible types: character varying and character varying[].

2025-04-25 09:52:58,014: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:8333383(Query-id: 1525155):
Error Message:ERROR:  foreign key constraint "idEscola" cannot be implemented
Key columns "idEscola" and "idEscola" are of incompatible types: integer and character varying[]. 

SQL state: 42804
Detail: Key columns "idEscola" and "idEscola" are of incompatible types: integer and character varying[].

2025-04-25 09:56:29,154: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:3753814(Query-id: 1787356):
Error Message:NOTICE:  relation "Estado" already exists, skipping
NOTICE:  relation "Município" already exists, skipping
NOTICE:  relation "Escola" already exists, skipping
NOTICE:  relation "IndicadoresAlunos" already exists, skipping
NOTICE:  relation "ClassificacaoSocioEconomica" already exists, skipping
NOTICE:  relation "NivelEscolariade" already exists, skipping
NOTICE:  relation "PorcentagemClassificacaoAlunos" already exists, skipping
NOTICE:  relation "TaxasAprovacao" already exists, skipping
NOTICE:  relation "NotaIDEB" already exists, skipping
NOTICE:  relation "NotaSAEB" already exists, skipping
NOTICE:  relation "AprovacaoSerie" already exists, skipping

ERROR:  constraint "idMunicipio" for relation "Escola" already exists 

SQL state: 42710

2025-04-25 09:57:19,168: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #4 - CONN:3753814(Query-id: 7186971):
Error Message:NOTICE:  relation "Estado" already exists, skipping
NOTICE:  relation "Município" already exists, skipping
NOTICE:  relation "Escola" already exists, skipping
NOTICE:  relation "IndicadoresAlunos" already exists, skipping
NOTICE:  relation "ClassificacaoSocioEconomica" already exists, skipping
NOTICE:  relation "NivelEscolariade" already exists, skipping
NOTICE:  relation "PorcentagemClassificacaoAlunos" already exists, skipping
NOTICE:  relation "TaxasAprovacao" already exists, skipping
NOTICE:  relation "NotaIDEB" already exists, skipping
NOTICE:  relation "NotaSAEB" already exists, skipping
NOTICE:  relation "AprovacaoSerie" already exists, skipping

ERROR:  constraint "idMunicipio" for relation "Escola" already exists 

SQL state: 42710


